import Header from './(components)/(Header)/header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col h-screen max-h-screen'>
          <Header />
          <div className='overflow-y-auto flex-grow bg-page text-default-text'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
